config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'messages/show'
  get 'messages/create'

  devise_for :users
  root 'static_pages#index'
  delete 'users/sign_out', to: 'devise/sessions#destroy'
  resources :events, only: [:show, :new, :create]
  resources :messages, only: [:new, :create]
  resources :contacts, only: [:new], path: '/contact', controller: 'static_pages'
  resources :users do
    member do
      get 'profile'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :event
  after_create :send_participation_email
  # Attribut supplémentaire
  validates :stripe_customer_id, presence: true

  private
  
  def send_participation_email
    EventMailer.partiipation_email(self.user, self.event).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :attendances, dependent: :destroy

  # Validations
  validates :start_date, presence: true
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :title, presence: true, length: { minimum: 5, maximum: 140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 1000 }
  validates :location, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :generate_fake_email
  after_update :generate_fake_email_if_needed

  # Associations
  has_many :events, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'recipient_id'

  after_create :send_welcome_email

  # Make first_name, last_name, age, and description optional during registration
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :first_name, presence: true, on: :update
  validates :last_name, presence: true, on: :update
  validates :age, presence: true, on: :update
  validates :description, presence: true, on: :update

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end

  def generate_fake_email_if_needed
    if first_name_changed? || last_name_changed?
      generate_fake_email
    end
  end

  def generate_fake_email
    if self.first_name.present? && self.last_name.present?
      first_name = self.first_name.downcase
      last_initial = self.last_name.downcase[0]
      self.fake_email = "#{first_name}.#{last_initial}@eventbrite.com"
      self.save
    else
      self.fake_email = "user@example.com"
    end
  end
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb

class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :exception
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age, :description])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :age, :description])
    end
  end
  

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def show
        @event = Event.find(params[:id])
    end

    def new
    @event = Event.new
    end

    def create
    @event = current_user.events.build(event_params)

     if @event.save
      redirect_to @event, notice: "L'événement a été créé avec succès."
     else
      render :new
    end
     end

  private

     def event_params
    params.require(:event).permit(:title, :description, :start_date, :duration, :price, :location)
     end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = current_user.received_messages
  end

  def show
    @message = Message.find(params[:id])
    # Vérifier si l'utilisateur actuel est le destinataire du message
    if @message.recipient == current_user
      @message.mark_as_read! unless @message.read?
    else
      # Rediriger ou afficher un message d'erreur si l'utilisateur n'est pas autorisé à voir ce message
    end
  end

  def new
    @message = Message.new
    @recipient = User.find(params[:recipient_id])
  end # Ajout de l'end manquant

  def create
    @message = Message.new(message_params)
    @message.sender = current_user
    if @message.save
      redirect_to @message, notice: 'Message sent successfully.'
    else
      flash.now[:alert] = 'Invalid recipient'
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:recipient_id, :subject, :body)
  end

  def user_valid?(recipient_id)
    User.exists?(recipient_id)
  end
end

app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Vous êtes connecté."
    else
      flash.now[:alert] = "Adresse e-mail ou mot de passe incorrect."
      redirect_to new_user_registration_path(email: params[:session][:email])
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Vous êtes déconnecté."
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end
  def contact
  end
  def welcome
    @user = current_user
  end
  def index
    @events = Event.all
    @users = User.all
    @users_with_events = User.includes(:events).where.not(events: { id: nil }).distinct
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  
    def show
        @user = current_user || User.find(params[:id])
    end
    def profile
        @user = User.find(params[:id])
    end

    def index
        @users = User.all

    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Créer un nouvel événement</title>
  <!-- Ajoute les liens vers Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    /* Ajoute des styles personnalisés */
    .form-control {
      margin-bottom: 10px;
    }

    .btn-primary {
      background-color: #007bff;
      border-color: #007bff;
    }

    .btn-primary:hover {
      background-color: #0056b3;
      border-color: #0056b3;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Créer un nouvel événement</h1>
    <%= form_with(model: @event, local: true) do |form| %>
      <!-- Champ pour le titre de l'événement -->
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <!-- Champ pour la description de l'événement -->
      <div class="mb-3">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_area :description, class: "form-control" %>
      </div>
      <!-- Champ pour la date de début de l'événement -->
      <div class="mb-3">
        <%= form.label :start_date, class: "form-label" %>
        <%= form.date_field :start_date, class: "form-control" %>
      </div>
      <!-- Champ pour la durée de l'événement -->
      <div class="mb-3">
        <%= form.label :duration, class: "form-label" %>
        <%= form.number_field :duration, class: "form-control" %>
      </div>
      <!-- Champ pour le prix de l'événement -->
      <div class="mb-3">
        <%= form.label :price, class: "form-label" %>
        <%= form.number_field :price, class: "form-control" %>
      </div>
      <!-- Champ pour le lieu de l'événement -->
      <div class="mb-3">
        <%= form.label :location, class: "form-label" %>
        <%= form.text_field :location, class: "form-control" %>
      </div>
      <!-- Bouton pour soumettre le formulaire -->
      <%= form.submit "Créer l'événement", class: "btn btn-primary" %>
    <% end %>
  </div>
  
  <!-- Ajoute le script Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Détails de l'événement</title>
  <!-- Ajoute les liens vers Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    /* Ajoute des styles personnalisés pour la page d'événement */
    .event-details {
      margin-top: 50px;
    }

    .event-details .card {
      border-radius: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .event-details .card-header {
      background-color: #007bff;
      color: #fff;
      border-radius: 10px 10px 0 0;
    }

    .event-details .card-body {
      padding: 20px;
    }

    .event-details .card-title {
      font-size: 1.5rem;
      color: #333;
    }

    .event-details .card-text {
      color: #666;
    }

    .event-details .btn {
      margin-top: 20px;
    }
  </style>
</head>
<body>
  <div class="container event-details">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Détails de l'événement</h3>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= @event.title %></h5>
        <p class="card-text"><strong>Date de début :</strong> <%= @event.start_date %></p>
        <p class="card-text"><strong>Durée :</strong> <%= @event.duration %> heures</p>
        <p class="card-text"><strong>Description :</strong> <%= @event.description %></p>
        <p class="card-text"><strong>Prix :</strong> <%= @event.price %> euros</p>
        <p class="card-text"><strong>Lieu :</strong> <%= @event.location %></p>
        <!-- Ajoute un lien de retour à la page d'accueil -->
        <%= link_to "Retour à la liste des événements", root_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>

  <!-- Ajoute le script Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
@import url('https://fonts.googleapis.com/css2?family=Jersey+25&family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap');
</style>
  </head>

    <header class="noto-sans-header">
    <%= render partial: 'shared/navbar' %>
    <img src="https://www.zarla.com/images/zarla-top-events-1x1-2400x2400-20211123-dkkcxd64j3w7xj6p3g7c.png?crop=1:1,smart&width=250&dpr=2" alt="Logo" style="max-width: 200px; margin: 20px auto; display: block;">

    </header>
  <body class="noto-sans-body">

    <%= yield %>
  </body>
</html>

app/views/messages/create.html.erb
<%= form_with(model: @message, url: messages_path, method: :post) do |form| %>
    <div>
      <%= form.label :subject %>
      <%= form.text_field :subject %>
    </div>
    <div>
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/messages/index.html.erb
<h1>Messages</h1>

<% @messages.each do |message| %>
  <div>
    <%= link_to message.subject, message_path(message) %>
    <p><%= message.body %></p>
  </div>
<% end %>

app/views/messages/show.html.erb
<h1><%= @message.subject %></h1>
<p><%= @message.body %></p>

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navbar</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <style>
        /* Style CSS */
        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #f1f1f1;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .dropdown:hover .dropbtn {
            background-color: #3e8e41;
        }

        /* Background gradient */
        .navbar {
            background: linear-gradient(to right, #FFD700, #D4AF37);
        }

        /* Text color */
        .navbar-brand,
        .nav-link {
            color: black !important;
        }

        /* Adjust dropdown position */
        .dropdown-adjust {
            right: 0;
        }
    </style>
</head>
<body>

<!-- Navbar -->
<nav class="pl-4 navbar navbar-expand-lg navbar-dark justify-content-between">
  <a class="navbar-brand mr-auto" href="#">Event Brite</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">Accueil <span class="sr-only"></span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/users">Liste des utilisateurs</a>
      </li>
      <li class="nav-item">
      <a class="nav-link" href="<%= new_event_path %>">Créer un événement</a>
    </li>
    
    </ul>

    <!-- Condition pour afficher les liens en fonction de l'état de l'utilisateur -->
    <% if current_user %>
      <!-- Dropdown for profile and logout -->
      <div class="dropdown dropdown-adjust">
        <a class="nav-link dropdown-toggle" href="<%= user_path(current_user) %>" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mon Compte
        </a>
        <div class="dropdown-content" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="<%= user_path(current_user) %>">Voir mon profil</a>
          <a class="dropdown-item" href="<%= edit_user_registration_path %>">Modifier mon profil</a>
          <!-- Bouton de déconnexion dans votre dropdown -->

          <li class="nav-item">
          <!-- Formulaire de déconnexion -->
          <%= form_tag(destroy_user_session_path, method: :delete) do %>
            <%= button_tag(type: 'submit', class: 'nav-link', style: 'background: none; border: none; cursor: pointer;') do %>
              Se déconnecter
            <% end %>
          <% end %>
        </li>

        </div>
      </div>
    <% else %>
      <!-- Dropdown for sign up and sign in -->
      <div class="dropdown dropdown-adjust">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          S'inscrire / Se connecter
        </a>
        <div class="dropdown-content" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= new_user_registration_path %>">S'inscrire</a>
          <a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a>
        </div>
      </div>
    <% end %>
  </div>
</nav>

<!-- Bootstrap JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<!-- Ajoutez ce script à votre vue ou à un fichier JavaScript externe -->


</body>
</html>

app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>

    <style>
        body, html {
            height: 100%;
            margin: 0;
            padding: 0;
            color: white;
        }
        .container {
            display: flex;
            align-items: stretch;
            height: 100%;
        }
        .content {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            width: 400px;
            margin-right: auto; /* Pour pousser le contenu vers la gauche */
            display: flex;
            flex-direction: column; /* Pour empiler les éléments à l'intérieur */
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }
        input[type="text"],
        input[type="email"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        textarea {
            height: 100px;
        }
        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        button:hover {
            background-color: #45a049;
        }
        .contact-info {
            text-align: center;
            padding: 20px;
            background-color: #f4f4f4;
            width: 100%; /* Ajuster la largeur pour correspondre à celle du formulaire */
            margin-top: 20px; /* Ajout de marge pour séparer du formulaire */
        }
        .contact-email {
            font-weight: bold;
            color: #333;
        }
        .image {
            flex: 1;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: #f4f4f4;
        }
        .image img {
            max-width: 100%; /* Pour que l'image reste dans la largeur de son conteneur */
            max-height: 100%; /* Pour que l'image reste dans la hauteur de son conteneur */
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="content">
            <form action="/send_email" method="POST">
                <h1>Contactez nous !</h1>
                <label for="name">Votre Nom:</label><br>
                <input type="text" id="name" name="name" required><br>
                
                <label for="email">Votre email:</label><br>
                <input type="email" id="email" name="email" required><br>
                
                <label for="message">Message:</label><br>
                <textarea id="message" name="message" rows="4" required></textarea><br>
                
                <button type="submit">Send Message</button>
            </form>
            <div class="contact-info">
                <p>Pour toute question, veuillez contacter : <span class="contact-email">contactus.eventbrite@eventbrite.com</span></p>
            </div>
        </div>
    </div>
</body>
</html>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accueil</title>
  <!-- Ajoute les liens vers Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    /* Ajoute des styles personnalisés pour les cards */
    .card {
      border-radius: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      transition: box-shadow 0.3s ease;
    }
    body {
      color: white;
    }
    .card:hover {
      box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }

    .card-title {
      font-size: 1.2rem;
      color: black;
      margin-bottom: 10px;
    }

    .card-text {
      color: black;
    }

    .btn-primary {
      background-color: #007bff;
      border-color: #007bff;
    }

    .btn-primary:hover {
      background-color: #0056b3;
      border-color: #0056b3;
    }
  </style>
</head>
<body>
  <div class="container">
    <% if current_user %>
      <h1>Bienvenue <%= current_user.first_name %>!</h1>
      <p>Sur notre site d'évènements !</p>
      <%= link_to "Créer un événement", new_event_path, class: "btn btn-primary mb-3" %>
    <% else %>
      <h1>Bienvenue sur notre site d'évènements !</h1>
    <% end %>
    <!-- Affichage des événements -->
    <h2>Liste des événements :</h2>
    <div class="row">
      <% @events.each do |event| %>
        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= event.title %></h5>
              <p class="card-text"><strong>Créé par :</strong> <%= link_to event.user.full_name, profile_user_path(event.user) %></p>
              <p class="card-text"><%= event.description %></p>
              <p class="card-text"><strong>Début :</strong> <%= event.start_date %></p>
              <p class="card-text"><strong>Durée :</strong> <%= event.duration %> heures</p>
              <p class="card-text"><strong>Prix :</strong> <%= event.price %> euros</p>
              <p class="card-text"><strong>Lieu :</strong> <%= event.location %></p>
              <%= link_to "Voir plus", event, class: "btn btn-info" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  
  <!-- Ajoute le script Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->
<h1>Liste des utilisateurs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Prénom</th>
      <th>Nom de famille</th>
      <th>Âge</th>
      <th>Adresse e-mail</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.age %></td>
        <td><%= user.fake_email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/profile.html.erb
<!-- users/profile.html.erb -->

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2>Profil de <%= @user.full_name %></h2>

      <div class="field">
        <strong>Email:</strong>
        <%= @user.fake_email %>
      </div>

      <div class="field">
        <strong>Prénom:</strong>
        <%= @user.first_name %>
      </div>

      <div class="field">
        <strong>Nom de famille:</strong>
        <%= @user.last_name %>
      </div>

      <div class="field">
        <strong>Âge:</strong>
        <%= @user.age %>
      </div>

      <div class="field">
        <strong>Description:</strong>
        <%= @user.description %>
      </div>

      <%= link_to "Contacter #{@user.full_name}", new_message_path(recipient_id: @user.id), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2>Mon profil</h2>

      <div class="field">
        <strong>Email:</strong>
        <%= @user.email %>
      </div>

      <div class="field">
        <strong>Email EventBrite:</strong>
        <%= @user.fake_email %>
      </div>

      <div class="field">
        <strong>Prénom:</strong>
        <%= @user.first_name %>
      </div>

      <div class="field">
        <strong>Nom de famille:</strong>
        <%= @user.last_name %>
      </div>

      <div class="field">
        <strong>Âge:</strong>
        <%= @user.age %>
      </div>

      <div class="field">
        <strong>Description:</strong>
        <%= @user.description %>
      </div>

      <%= link_to "Modifier mon profil", edit_user_registration_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>